apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: agenda
  name: {{ .Release.Name }}-api
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-api
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-api
    spec:
      containers:
        - name: agenda-api
          image: {{ .Values.api.deployment.image }}:{{ .Values.api.deployment.tag }}
          imagePullPolicy: {{ .Values.api.deployment.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.api.deployment.port }}
              name: {{ .Values.api.deployment.portName }}
          env:
          - name: MONGODB_DBNAME
            value: {{ .Values.configMap.data.MONGO_INITDB_DATABASE }}
          - name: MONGODB_USER
            value: {{ .Values.configMap.data.MONGO_INITDB_USERNAME }}
          - name: MONGODB_PASSWORD
            value: {{ .Values.configMap.data.MONGO_INITDB_PASSWORD }}
          - name: MONGODB_HOST
            value: {{ .Release.Name }}-db-mongo
          - name: MONGODB_PORT
            value: "{{ .Values.configMap.data.MONGO_PORT }}"
          
          resources:
            limits:
              memory: 4Gi
              cpu: "2"