apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: {{ .Values.namespace  }}
  name: {{ .Release.Name }}-{{ .Values.mongo.persistentVolumeClaim.name }}
spec:
  volumeName: {{ .Release.Name }}-{{ .Values.mongo.persistentVolume.name }}
  storageClassName: {{ .Values.mongo.persistentVolumeClaim.storageClassName }}
  {{- with .Values.mongo.persistentVolumeClaim.accessModes }}
  accessModes:
    {{- toYaml . | nindent 8 }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.mongo.persistentVolumeClaim.resources.requests.storage }}