apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Release.Name }}-db-mongo
  labels:
    app: {{ .Release.Name }}-db-mongo
spec:
  type: {{ .Values.mongo.service.type }}
  selector:
    app: {{ .Release.Name }}-db-mongo
  ports:
  - protocol: {{ .Values.mongo.service.protocol  }}
    port: {{ .Values.mongo.service.port }}
    targetPort: {{ .Values.mongo.service.targetPort }}