apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.persistentVolume.api.name }}
  labels:
    type: local
spec:
  claimRef:
    name: {{ .Values.persistentVolumeClaim.api.name }}
  storageClassName: {{ .Values.persistentVolume.api.storageClassName }}
  capacity:
    storage: {{ .Values.persistentVolume.api.capacity }}
  accessModes:
    - {{ .Values.persistentVolume.api.accessModes }}
  hostPath:
    path: {{ .Values.persistentVolume.api.hostPath }}

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.persistentVolume.db.name }}
  labels:
    type: local
spec:
  claimRef:
    name: {{ .Values.persistentVolumeClaim.db.name }}
  storageClassName: {{ .Values.persistentVolume.db.storageClassName }}
  capacity:
    storage: {{ .Values.persistentVolume.db.capacity }}
  accessModes:
    - {{ .Values.persistentVolume.db.accessModes }}
  hostPath:
    path: {{ .Values.persistentVolume.db.hostPath }}