apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.api.name  }}
spec:
  type: {{ .Values.service.api.type }} 
  selector:
    app: {{ .Values.deployment.api.appName }}
  ports:
    - name: {{ .Values.service.api.port.name }}
      protocol: {{ .Values.service.api.port.protocol  }}
      port: {{ .Values.service.api.port.number }}
      targetPort: {{ .Values.service.api.port.targetPort }}
      nodePort: {{ .Values.service.api.port.nodePort }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.db.name  }}
  labels:
    app: {{ .Values.service.db.name  }}
spec:
  type: {{ .Values.service.db.type }}
  selector:
    app: {{ .Values.deployment.db.dbName }}
  ports:
  - protocol: {{ .Values.service.db.port.protocol }}
    port: {{ .Values.service.db.port.number }}
    targetPort: {{ .Values.service.db.port.targetPort }}
    nodePort: {{ .Values.service.db.port.nodePort }}