apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: agenda
  name: agenda-db-mongo-data-persistent-volume
  labels:
    type: local
spec:
  claimRef:
    namespace: default
    name: agenda-db-mongo-data-persistent-volume-claim
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/ricardo/Documents/personal/agenda-app/mongo-data"
    type: DirectoryOrCreate