apiVersion: v1
kind: Service
metadata:
  namespace: agenda
  name: agenda-db-service
  labels:
    app: agenda-db-service
spec:
  type: NodePort
  selector:
    app: agenda-db
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017
    nodePort: 30017