apiVersion: v1
kind: Service
metadata:
  labels:
    app: agendadb
  name: agendadb-service
spec:
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    app: agendadb
  clusterIP: None

---
apiVersion: v1
kind: Service
metadata:
  name: agenda-service
  labels:
    app: agenda-service
spec:
  type: ClusterIP
  selector:
    app: agenda-api
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
