namespace: agenda
mongo:
  deployment:
    tag: latest
    port: 27017
    resources:
      limits:
        memory: 4Gi
        cpu: "2"
  service:
    type: NodePort
    protocol: TCP
    port: 27017
    targetPort: 27017
    nodePort: 30017
  persistentVolume:
    name: mongo-data-persistent-volume
    type: local
    storageClassName: manual
    capacity:
      storage: 5Gi
    accessModes: ["ReadWriteOnce"]
    host: 
      path: "/home/ricardo/Documents/personal/agenda-app/mongo-data"
      type: DirectoryOrCreate
  persistentVolumeClaim:
    name: mongo-data-persistent-volume-claim
    storageClassName: manual
    accessModes: ["ReadWriteOnce"]
    resources:
      requests:
        storage: 5Gi
api:
  deployment:
    tag: "0.1.0"
    image: rluisb/agenda-api
    port: 8080
    portName: "http"
    serviceType: LoadBalancer
    imagePullPolicy: Always
    volume:
      name: source-code-storage
      mountPath: /app
  service:
    portName: "http"
    type: NodePort
    protocol: TCP
    port: 80
    targetPort: 8080
    nodePort: 30000
  ingress:
    enabled: false
    imageClassName: nginx
    hosts: ["10.102.66.15.nip.io"]

configMap:
  data:
    MONGO_INITDB_ROOT_USERNAME: root
    MONGO_INITDB_ROOT_PASSWORD: root
    MONGO_INITDB_DATABASE: agenda
    MONGO_INITDB_USERNAME: agenda
    MONGO_INITDB_PASSWORD: agenda
    MONGO_PORT: "27017"
    