apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: agenda-api-source-code-persisent-volume-claim
spec:
  volumeName: agenda-api-source-code-persisent-volume
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi