apiVersion: v1
kind: Service
metadata:
  name: agenda-api-service
spec:
  type: NodePort
  selector:
    app: agenda-api
  ports:
    - name: "http"
      protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30000